// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ViewModel.tt
using System;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Windows.Input;
using WPAppStudio;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;
using WPAppStudio.Localization;
using WPAppStudio.Repositories;
using WPAppStudio.Services;
using WPAppStudio.Services.Interfaces;
using WPAppStudio.Shared;
using WPAppStudio.ViewModel.Base;
using WPAppStudio.ViewModel.Interfaces;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of Account_List ViewModel.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public partial class Account_ListViewModel : BindableBase, IAccount_ListViewModel
    {       

		private readonly IDialogService _dialogService;
		private readonly INavigationService _navigationService;
		private readonly IAccountCollection _accountCollection;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="Account_ListViewModel" /> class.
        /// </summary>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="accountCollection">The Account Collection.</param>
        public Account_ListViewModel(IDialogService dialogService, INavigationService navigationService, IAccountCollection accountCollection)
        {
			_dialogService = dialogService;
			_navigationService = navigationService;
			_accountCollection = accountCollection;
        }
		

		private ObservableCollection<AccountCollectionSchema> _account_ListListControlCollection;

        /// <summary>
        /// Account_ListListControlCollection property.
        /// </summary>		
        public ObservableCollection<AccountCollectionSchema> Account_ListListControlCollection
        {
            get
            {
                if(_account_ListListControlCollection == null)
					_account_ListListControlCollection = _accountCollection.GetData();
				return _account_ListListControlCollection;     
            }
            set
            {
                SetProperty(ref _account_ListListControlCollection, value);
            }
        }

		private AccountCollectionSchema _selectedAccount_ListListControlCollection;

        /// <summary>
        /// SelectedAccount_ListListControlCollection property.
        /// </summary>		
        public AccountCollectionSchema SelectedAccount_ListListControlCollection
        {
            get
            {
				return _selectedAccount_ListListControlCollection;
            }
            set
            {
                _selectedAccount_ListListControlCollection = value;
                if (value != null)
                    _navigationService.NavigateTo<IAccount_DetailViewModel>(_selectedAccount_ListListControlCollection);
            }
        }
    }
}
