// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ViewModel.tt
using System;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Windows.Input;
using WPAppStudio;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;
using WPAppStudio.Localization;
using WPAppStudio.Repositories;
using WPAppStudio.Services;
using WPAppStudio.Services.Interfaces;
using WPAppStudio.Shared;
using WPAppStudio.ViewModel.Base;
using WPAppStudio.ViewModel.Interfaces;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of Connection_List ViewModel.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public partial class Connection_ListViewModel : BindableBase, IConnection_ListViewModel
    {       

		private readonly IDialogService _dialogService;
		private readonly INavigationService _navigationService;
		private readonly IConnectionCollection _connectionCollection;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="Connection_ListViewModel" /> class.
        /// </summary>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="connectionCollection">The Connection Collection.</param>
        public Connection_ListViewModel(IDialogService dialogService, INavigationService navigationService, IConnectionCollection connectionCollection)
        {
			_dialogService = dialogService;
			_navigationService = navigationService;
			_connectionCollection = connectionCollection;
        }
		

		private ObservableCollection<ConnectionCollectionSchema> _connection_ListListControlCollection;

        /// <summary>
        /// Connection_ListListControlCollection property.
        /// </summary>		
        public ObservableCollection<ConnectionCollectionSchema> Connection_ListListControlCollection
        {
            get
            {
                if(_connection_ListListControlCollection == null)
					_connection_ListListControlCollection = _connectionCollection.GetData();
				return _connection_ListListControlCollection;     
            }
            set
            {
                SetProperty(ref _connection_ListListControlCollection, value);
            }
        }

		private ConnectionCollectionSchema _selectedConnection_ListListControlCollection;

        /// <summary>
        /// SelectedConnection_ListListControlCollection property.
        /// </summary>		
        public ConnectionCollectionSchema SelectedConnection_ListListControlCollection
        {
            get
            {
				return _selectedConnection_ListListControlCollection;
            }
            set
            {
                _selectedConnection_ListListControlCollection = value;
                if (value != null)
                    _navigationService.NavigateTo<IConnection_DetailViewModel>(_selectedConnection_ListListControlCollection);
            }
        }
    }
}
