// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ViewModel.tt
using System;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Windows.Input;
using WPAppStudio;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;
using WPAppStudio.Localization;
using WPAppStudio.Repositories;
using WPAppStudio.Services;
using WPAppStudio.Services.Interfaces;
using WPAppStudio.Shared;
using WPAppStudio.ViewModel.Base;
using WPAppStudio.ViewModel.Interfaces;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of People_Detail ViewModel.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public partial class People_DetailViewModel : BindableBase, IPeople_DetailViewModel, INavigable
    {       

		private readonly IDialogService _dialogService;
		private readonly INavigationService _navigationService;
		private readonly ISpeechService _speechService;
		private readonly IShareService _shareService;
		private readonly ILiveTileService _liveTileService;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="People_DetailViewModel" /> class.
        /// </summary>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="speechService">The Speech Service.</param>
        /// <param name="shareService">The Share Service.</param>
        /// <param name="liveTileService">The Live Tile Service.</param>
        public People_DetailViewModel(IDialogService dialogService, INavigationService navigationService, ISpeechService speechService, IShareService shareService, ILiveTileService liveTileService)
        {
			_dialogService = dialogService;
			_navigationService = navigationService;
			_speechService = speechService;
			_shareService = shareService;
			_liveTileService = liveTileService;
        }
		

		private PeopleCollectionSchema _currentPeopleCollectionSchema;

        /// <summary>
        /// CurrentPeopleCollectionSchema property.
        /// </summary>		
        public PeopleCollectionSchema CurrentPeopleCollectionSchema
        {
            get
            {
				return _currentPeopleCollectionSchema;
            }
            set
            {
                SetProperty(ref _currentPeopleCollectionSchema, value);
            }
        }

        /// <summary>
        /// Delegate method for the TextToSpeechPeople_DetailStaticControlCommand command.
        /// </summary>
        public  void TextToSpeechPeople_DetailStaticControlCommandDelegate() 
        {
	
				_speechService.TextToSpeech(CurrentPeopleCollectionSchema.Subtitle + " " + CurrentPeopleCollectionSchema.Description);
        }
		

        private ICommand _textToSpeechPeople_DetailStaticControlCommand;

        /// <summary>
        /// Gets the TextToSpeechPeople_DetailStaticControlCommand command.
        /// </summary>
        public ICommand TextToSpeechPeople_DetailStaticControlCommand
        {
            get { return _textToSpeechPeople_DetailStaticControlCommand = _textToSpeechPeople_DetailStaticControlCommand ?? new DelegateCommand(TextToSpeechPeople_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the SharePeople_DetailStaticControlCommand command.
        /// </summary>
        public  void SharePeople_DetailStaticControlCommandDelegate() 
        {
	
				_shareService.Share(CurrentPeopleCollectionSchema.Subtitle, CurrentPeopleCollectionSchema.Description);
        }
		

        private ICommand _sharePeople_DetailStaticControlCommand;

        /// <summary>
        /// Gets the SharePeople_DetailStaticControlCommand command.
        /// </summary>
        public ICommand SharePeople_DetailStaticControlCommand
        {
            get { return _sharePeople_DetailStaticControlCommand = _sharePeople_DetailStaticControlCommand ?? new DelegateCommand(SharePeople_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the PinToStartPeople_DetailStaticControlCommand command.
        /// </summary>
        public  void PinToStartPeople_DetailStaticControlCommandDelegate() 
        {
	
				_liveTileService.PinToStart(typeof(IPeople_DetailViewModel), CreateTileInfoPeople_DetailStaticControl());
        }
		

        private ICommand _pinToStartPeople_DetailStaticControlCommand;

        /// <summary>
        /// Gets the PinToStartPeople_DetailStaticControlCommand command.
        /// </summary>
        public ICommand PinToStartPeople_DetailStaticControlCommand
        {
            get { return _pinToStartPeople_DetailStaticControlCommand = _pinToStartPeople_DetailStaticControlCommand ?? new DelegateCommand(PinToStartPeople_DetailStaticControlCommandDelegate); }
        }
		public object NavigationContext
        {
            set
            {              
                if (!(value is PeopleCollectionSchema)) { return; }
                
                CurrentPeopleCollectionSchema = value as PeopleCollectionSchema;
            }
        }
        /// <summary>
        /// Initializes a <see cref="TileInfo" /> object for the People_DetailStaticControl control.
        /// </summary>
		/// <returns>A <see cref="TileInfo" /> object.</returns>
        public TileInfo CreateTileInfoPeople_DetailStaticControl()
        {
            var tileInfo = new TileInfo
            {
                CurrentId = CurrentPeopleCollectionSchema.Id.ToString(),
                Title = CurrentPeopleCollectionSchema.Subtitle,
                BackTitle = CurrentPeopleCollectionSchema.Subtitle,
                BackContent = CurrentPeopleCollectionSchema.Description,
                Count = 0,
                BackgroundImagePath = CurrentPeopleCollectionSchema.Image,
                BackBackgroundImagePath = CurrentPeopleCollectionSchema.Image,
                LogoPath = "Logo-64afe68b-41c7-4545-a549-8de070ba8299.png"
            };
            return tileInfo;
        }
    }
}
