// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ViewModel.tt
using System;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Windows.Input;
using WPAppStudio;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;
using WPAppStudio.Localization;
using WPAppStudio.Repositories;
using WPAppStudio.Services;
using WPAppStudio.Services.Interfaces;
using WPAppStudio.Shared;
using WPAppStudio.ViewModel.Base;
using WPAppStudio.ViewModel.Interfaces;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of Rooms_Detail ViewModel.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public partial class Rooms_DetailViewModel : BindableBase, IRooms_DetailViewModel, INavigable
    {       

		private readonly IDialogService _dialogService;
		private readonly INavigationService _navigationService;
		private readonly ISpeechService _speechService;
		private readonly IShareService _shareService;
		private readonly ILiveTileService _liveTileService;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="Rooms_DetailViewModel" /> class.
        /// </summary>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="speechService">The Speech Service.</param>
        /// <param name="shareService">The Share Service.</param>
        /// <param name="liveTileService">The Live Tile Service.</param>
        public Rooms_DetailViewModel(IDialogService dialogService, INavigationService navigationService, ISpeechService speechService, IShareService shareService, ILiveTileService liveTileService)
        {
			_dialogService = dialogService;
			_navigationService = navigationService;
			_speechService = speechService;
			_shareService = shareService;
			_liveTileService = liveTileService;
        }
		

		private RoomsRepoCollectionSchema _currentRoomsRepoCollectionSchema;

        /// <summary>
        /// CurrentRoomsRepoCollectionSchema property.
        /// </summary>		
        public RoomsRepoCollectionSchema CurrentRoomsRepoCollectionSchema
        {
            get
            {
				return _currentRoomsRepoCollectionSchema;
            }
            set
            {
                SetProperty(ref _currentRoomsRepoCollectionSchema, value);
            }
        }

        /// <summary>
        /// Delegate method for the TextToSpeechRooms_DetailStaticControlCommand command.
        /// </summary>
        public  void TextToSpeechRooms_DetailStaticControlCommandDelegate() 
        {
	
				_speechService.TextToSpeech(CurrentRoomsRepoCollectionSchema.Subtitle + " " + CurrentRoomsRepoCollectionSchema.Description);
        }
		

        private ICommand _textToSpeechRooms_DetailStaticControlCommand;

        /// <summary>
        /// Gets the TextToSpeechRooms_DetailStaticControlCommand command.
        /// </summary>
        public ICommand TextToSpeechRooms_DetailStaticControlCommand
        {
            get { return _textToSpeechRooms_DetailStaticControlCommand = _textToSpeechRooms_DetailStaticControlCommand ?? new DelegateCommand(TextToSpeechRooms_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the ShareRooms_DetailStaticControlCommand command.
        /// </summary>
        public  void ShareRooms_DetailStaticControlCommandDelegate() 
        {
	
				_shareService.Share(CurrentRoomsRepoCollectionSchema.Subtitle, CurrentRoomsRepoCollectionSchema.Description);
        }
		

        private ICommand _shareRooms_DetailStaticControlCommand;

        /// <summary>
        /// Gets the ShareRooms_DetailStaticControlCommand command.
        /// </summary>
        public ICommand ShareRooms_DetailStaticControlCommand
        {
            get { return _shareRooms_DetailStaticControlCommand = _shareRooms_DetailStaticControlCommand ?? new DelegateCommand(ShareRooms_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the PinToStartRooms_DetailStaticControlCommand command.
        /// </summary>
        public  void PinToStartRooms_DetailStaticControlCommandDelegate() 
        {
	
				_liveTileService.PinToStart(typeof(IRooms_DetailViewModel), CreateTileInfoRooms_DetailStaticControl());
        }
		

        private ICommand _pinToStartRooms_DetailStaticControlCommand;

        /// <summary>
        /// Gets the PinToStartRooms_DetailStaticControlCommand command.
        /// </summary>
        public ICommand PinToStartRooms_DetailStaticControlCommand
        {
            get { return _pinToStartRooms_DetailStaticControlCommand = _pinToStartRooms_DetailStaticControlCommand ?? new DelegateCommand(PinToStartRooms_DetailStaticControlCommandDelegate); }
        }
		public object NavigationContext
        {
            set
            {              
                if (!(value is RoomsRepoCollectionSchema)) { return; }
                
                CurrentRoomsRepoCollectionSchema = value as RoomsRepoCollectionSchema;
            }
        }
        /// <summary>
        /// Initializes a <see cref="TileInfo" /> object for the Rooms_DetailStaticControl control.
        /// </summary>
		/// <returns>A <see cref="TileInfo" /> object.</returns>
        public TileInfo CreateTileInfoRooms_DetailStaticControl()
        {
            var tileInfo = new TileInfo
            {
                CurrentId = CurrentRoomsRepoCollectionSchema.Subtitle,
                Title = CurrentRoomsRepoCollectionSchema.Subtitle,
                BackTitle = CurrentRoomsRepoCollectionSchema.Subtitle,
                BackContent = CurrentRoomsRepoCollectionSchema.Description,
                Count = 0,
                BackgroundImagePath = CurrentRoomsRepoCollectionSchema.Image,
                BackBackgroundImagePath = CurrentRoomsRepoCollectionSchema.Image,
                LogoPath = "Logo-64afe68b-41c7-4545-a549-8de070ba8299.png"
            };
            return tileInfo;
        }
    }
}
