// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.Collections.ObjectModel;
using System.Windows.Input;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// Account_Detail ViewModel interface.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public interface IAccount_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentAccountCollectionSchema property.
        /// </summary>
		AccountCollectionSchema CurrentAccountCollectionSchema { get; set; }

        
        /// <summary>
        /// Gets the TextToSpeechAccount_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechAccount_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareAccount_DetailStaticControlCommand command.
        /// </summary>
		ICommand ShareAccount_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartAccount_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartAccount_DetailStaticControlCommand { get; }

	}
}
