// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.Collections.ObjectModel;
using System.Windows.Input;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// Connection_Detail ViewModel interface.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public interface IConnection_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentConnectionCollectionSchema property.
        /// </summary>
		ConnectionCollectionSchema CurrentConnectionCollectionSchema { get; set; }

        
        /// <summary>
        /// Gets the TextToSpeechConnection_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechConnection_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareConnection_DetailStaticControlCommand command.
        /// </summary>
		ICommand ShareConnection_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartConnection_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartConnection_DetailStaticControlCommand { get; }

	}
}
