// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.Collections.ObjectModel;
using System.Windows.Input;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// Connection_List ViewModel interface.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public interface IConnection_ListViewModel
    {		
        /// <summary>
        /// Gets/Sets the Connection_ListListControlCollection property.
        /// </summary>
		ObservableCollection<ConnectionCollectionSchema> Connection_ListListControlCollection { get; set; }

        /// <summary>
        /// Gets/Sets the SelectedConnection_ListListControlCollection property.
        /// </summary>
		ConnectionCollectionSchema SelectedConnection_ListListControlCollection { get; set; }

	}
}
