// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.Collections.ObjectModel;
using System.Windows.Input;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// People_Detail ViewModel interface.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public interface IPeople_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentPeopleCollectionSchema property.
        /// </summary>
		PeopleCollectionSchema CurrentPeopleCollectionSchema { get; set; }

        
        /// <summary>
        /// Gets the TextToSpeechPeople_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechPeople_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the SharePeople_DetailStaticControlCommand command.
        /// </summary>
		ICommand SharePeople_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartPeople_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartPeople_DetailStaticControlCommand { get; }

	}
}
