// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.Collections.ObjectModel;
using System.Windows.Input;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// Rooms_List ViewModel interface.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public interface IRooms_ListViewModel
    {		
        /// <summary>
        /// Gets/Sets the Rooms_ListListControlCollection property.
        /// </summary>
		ObservableCollection<RoomsRepoCollectionSchema> Rooms_ListListControlCollection { get; set; }

        /// <summary>
        /// Gets/Sets the SelectedRooms_ListListControlCollection property.
        /// </summary>
		RoomsRepoCollectionSchema SelectedRooms_ListListControlCollection { get; set; }

        /// <summary>
        /// Gets/Sets the People_ListListControlCollection property.
        /// </summary>
		ObservableCollection<PeopleCollectionSchema> People_ListListControlCollection { get; set; }

        /// <summary>
        /// Gets/Sets the SelectedPeople_ListListControlCollection property.
        /// </summary>
		PeopleCollectionSchema SelectedPeople_ListListControlCollection { get; set; }

        /// <summary>
        /// Gets/Sets the SelectedSettingsMenuControl property.
        /// </summary>
		MenuItemData SelectedSettingsMenuControl { get; set; }

        
        /// <summary>
        /// Gets the RefreshRooms_ListListControlCollection command.
        /// </summary>
		ICommand RefreshRooms_ListListControlCollection { get; }

        
        /// <summary>
        /// Gets the SetLockScreenCommand command.
        /// </summary>
		ICommand SetLockScreenCommand { get; }

	}
}
