// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.Collections.ObjectModel;
using System.Windows.Input;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// Rooms_Detail ViewModel interface.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public interface IRooms_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentRoomsRepoCollectionSchema property.
        /// </summary>
		RoomsRepoCollectionSchema CurrentRoomsRepoCollectionSchema { get; set; }

        
        /// <summary>
        /// Gets the TextToSpeechRooms_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechRooms_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareRooms_DetailStaticControlCommand command.
        /// </summary>
		ICommand ShareRooms_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartRooms_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartRooms_DetailStaticControlCommand { get; }

	}
}
