// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   DataSource.tt
using System;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using WPAppStudio.Entities;
using WPAppStudio.Repositories.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// AccountCollection data source.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public class AccountCollection : IAccountCollection 
    {
        private readonly ObservableCollection<AccountCollectionSchema> _data = new ObservableCollection<AccountCollectionSchema>
		{
		};
	
		
        /// <summary>
        /// Retrieves the data from a static data source, in an observable collection of AccountCollectionSchema items.
        /// </summary>
        /// <returns>An observable collection of AccountCollectionSchema items.</returns>
        public ObservableCollection<AccountCollectionSchema> GetData()
        {		
            return _data;
        }
		
		/// <summary>
        /// Retrieves the data from a static data source, filtered by a filter specification, in an observable collection of AccountCollectionSchema items.
        /// </summary>
		/// <param name="filter">Filter operation specification</param>
        /// <returns>An observable collection of AccountCollectionSchema items.</returns>
        public ObservableCollection<AccountCollectionSchema> Search(FilterSpecification filter)
        {
            return Filter<AccountCollectionSchema>.FilterCollection(filter, _data);
        }
	}
}
