// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   DataSource.tt
using System;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using WPAppStudio.Entities;
using WPAppStudio.Repositories.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// ConnectionCollection data source.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public class ConnectionCollection : IConnectionCollection 
    {
        private readonly ObservableCollection<ConnectionCollectionSchema> _data = new ObservableCollection<ConnectionCollectionSchema>
		{
		};
	
		
        /// <summary>
        /// Retrieves the data from a static data source, in an observable collection of ConnectionCollectionSchema items.
        /// </summary>
        /// <returns>An observable collection of ConnectionCollectionSchema items.</returns>
        public ObservableCollection<ConnectionCollectionSchema> GetData()
        {		
            return _data;
        }
		
		/// <summary>
        /// Retrieves the data from a static data source, filtered by a filter specification, in an observable collection of ConnectionCollectionSchema items.
        /// </summary>
		/// <param name="filter">Filter operation specification</param>
        /// <returns>An observable collection of ConnectionCollectionSchema items.</returns>
        public ObservableCollection<ConnectionCollectionSchema> Search(FilterSpecification filter)
        {
            return Filter<ConnectionCollectionSchema>.FilterCollection(filter, _data);
        }
	}
}
