// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ServiceLocator.tt
using WPAppStudio.Ioc;
using WPAppStudio.Ioc.Interfaces;
using WPAppStudio.ViewModel;
using WPAppStudio.ViewModel.Interfaces;

namespace WPAppStudio.Services
{
    /// <summary>
    /// Implementation of the ViewModel locator service based on IoC.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public class ViewModelLocatorService
    {
        // IoC container
        private readonly IContainer _container;

        /// <summary>
        /// Initializes a new instance of the <see cref="ViewModelLocatorService" /> class.
        /// </summary>
        public ViewModelLocatorService()
        {
            _container = new Container();
        }

        /// <summary>
        /// Gets the reference to a Rooms_ListViewModel.
        /// </summary>
		public IRooms_ListViewModel Rooms_ListViewModel
        {
            get { return _container.Resolve<Rooms_ListViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a People_DetailViewModel.
        /// </summary>
		public IPeople_DetailViewModel People_DetailViewModel
        {
            get { return _container.Resolve<People_DetailViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a Rooms_DetailViewModel.
        /// </summary>
		public IRooms_DetailViewModel Rooms_DetailViewModel
        {
            get { return _container.Resolve<Rooms_DetailViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a Connection_ListViewModel.
        /// </summary>
		public IConnection_ListViewModel Connection_ListViewModel
        {
            get { return _container.Resolve<Connection_ListViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a Connection_DetailViewModel.
        /// </summary>
		public IConnection_DetailViewModel Connection_DetailViewModel
        {
            get { return _container.Resolve<Connection_DetailViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a Account_ListViewModel.
        /// </summary>
		public IAccount_ListViewModel Account_ListViewModel
        {
            get { return _container.Resolve<Account_ListViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a Account_DetailViewModel.
        /// </summary>
		public IAccount_DetailViewModel Account_DetailViewModel
        {
            get { return _container.Resolve<Account_DetailViewModel>(); }
        }
    }
}
